# Generated by Django 4.2.3 on 2023-08-18 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('instructions', models.JSONField(blank=True, null=True)),
                ('anomalies', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(blank=True, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docinfo', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('orderref', models.IntegerField()),
                ('personorderd', models.IntegerField(default=0)),
                ('grouporderd', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=0)),
                ('ordertype', models.CharField(blank=True, max_length=100)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('submitdate', models.DateField(blank=True, null=True)),
                ('functlocation', models.CharField(blank=True, max_length=200)),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('modelnumber', models.CharField(blank=True, max_length=200)),
                ('manufactserialnr', models.CharField(blank=True, max_length=200)),
                ('inventorynr', models.CharField(blank=True, max_length=25)),
                ('plannedtime', models.CharField(blank=True, max_length=25)),
                ('pmplannergrp', models.CharField(blank=True, max_length=25)),
                ('inspectionlot', models.CharField(blank=True, max_length=10)),
                ('instructions', models.JSONField(blank=True, null=True)),
                ('extention', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issuer', models.BooleanField(default=False)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('group', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
