# Generated by Django 4.2.3 on 2023-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internref',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
