# Generated by Django 4.2.3 on 2023-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0002_order_internref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='functlocation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='internref',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manufactserialnr',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modelnumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.IntegerField(),
        ),
    ]
