# Generated by Django 4.2.3 on 2023-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0003_remove_order_functlocation_remove_order_internref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='inventorynr',
        ),
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
