# Generated by Django 4.2.3 on 2023-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0005_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='internref',
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventoryref',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='equipment',
            name='nomenclature',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventorynr',
            field=models.IntegerField(),
        ),
    ]
