# Generated by Django 4.2.3 on 2023-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0006_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='nomenclature',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
