# Generated by Django 4.2.3 on 2023-08-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0007_alter_equipment_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
