# Generated by Django 4.2.3 on 2023-08-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0008_alter_order_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apgmp.equipment'),
        ),
    ]
