# Generated by Django 4.2.3 on 2023-09-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apgmp', '0010_delete_extention_rename_extention_order_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apgmp.equipment'),
        ),
    ]
